import type { PluginManifestEntry } from '@flow-tool/sdk'

export const builtInManifests: PluginManifestEntry[] = [
  {
    id: 'plugin-example-hello-world',
    name: 'Hello World Plugin',
    version: '0.0.1',
    type: 'app',
    permissions: ['network', 'storage', 'notification'],
    loader: () => import('@plugins/plugin-example-hello-world'),
  },
  {
    id: 'plugin-todo-list',
    name: 'Todo List',
    version: '0.0.1',
    type: 'app',
    permissions: ['storage'],
    category: '实用工具',
    tags: ['todo', 'list', 'task'],
    loader: () => import('@plugins/plugin-todo-list'),
  },
  {
    id: 'plugin-website-latency',
    name: '网站延迟测试',
    version: '0.1.0',
    description: '测试常用网站的网络延迟（Ping）',
    type: 'app',
    permissions: ['network'],
    tags: ['network', 'latency', 'ping'],
    category: '网络工具',
    loader: () => import('@plugins/plugin-website-latency'),
  },
  {
    id: 'plugin-uuid-generator',
    name: 'UUID 生成器',
    version: '0.1.0',
    description: '在线生成随机 UUID v4',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['uuid', 'random', 'generator'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-uuid-generator'),
  },
  {
    id: 'plugin-image-base64',
    name: '图片 Base64 互转',
    version: '0.1.0',
    description: '在线图片与 Base64 编码互相转换',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['image', 'base64', 'converter'],
    category: '编码工具',
    loader: () => import('@plugins/plugin-image-base64'),
  },
  {
    id: 'plugin-random-picker',
    name: '随机点名',
    version: '0.1.0',
    description: '在线名单随机点名工具',
    type: 'app',
    permissions: [],
    tags: ['random', 'picker', 'name'],
    category: '实用工具',
    loader: () => import('@plugins/plugin-random-picker'),
  },
  {
    id: 'plugin-text-ops',
    name: '文本集合运算',
    version: '0.1.0',
    description: '计算文本的交集、差集、并集',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['text', 'set', 'intersection', 'union', 'difference'],
    category: '文本工具',
    loader: () => import('@plugins/plugin-text-ops'),
  },
  {
    id: 'plugin-example-run-hello',
    name: 'run hello',
    version: '0.0.1',
    type: 'tool',
    loader: () => import('@plugins/plugin-example-run-hello'),
  },
  {
    id: 'plugin-json-formatter',
    name: 'JSON 格式化',
    version: '0.1.0',
    description: 'JSON 格式化、压缩、验证工具',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['json', 'format', 'minify', 'validate'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-json-formatter'),
  },
  {
    id: 'plugin-timestamp-converter',
    name: '时间戳转换',
    version: '0.1.0',
    description: 'Unix 时间戳与日期时间互转',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['timestamp', 'unix', 'date', 'converter'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-timestamp-converter'),
  },
  {
    id: 'plugin-base64-encoder',
    name: 'Base64 编解码',
    version: '0.1.0',
    description: '文本与 Base64 编码互转',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['base64', 'encode', 'decode', 'converter'],
    category: '编码工具',
    loader: () => import('@plugins/plugin-base64-encoder'),
  },
  {
    id: 'plugin-hash-generator',
    name: '哈希生成器',
    version: '0.1.0',
    description: '生成 SHA-1/SHA-256/SHA-384/SHA-512 哈希值',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['hash', 'sha', 'sha256', 'md5', 'generator'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-hash-generator'),
  },
  {
    id: 'plugin-color-converter',
    name: '颜色转换器',
    version: '0.1.0',
    description: 'HEX/RGB/HSL 颜色格式互转',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['color', 'hex', 'rgb', 'hsl', 'converter'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-color-converter'),
  },
  {
    id: 'plugin-regex-tester',
    name: '正则表达式测试',
    version: '0.1.0',
    description: '测试和调试正则表达式',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['regex', 'regexp', 'test', 'pattern'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-regex-tester'),
  },
]

export const pluginCategories = [
  {
    id: 'dev',
    label: '开发工具',
    description: '开发和调试相关工具',
    pluginIds: [
      'plugin-json-formatter',
      'plugin-timestamp-converter',
      'plugin-hash-generator',
      'plugin-regex-tester',
      'plugin-uuid-generator',
    ],
  },
  {
    id: 'encoding',
    label: '编码工具',
    description: '编码和格式转换工具',
    pluginIds: ['plugin-base64-encoder', 'plugin-image-base64'],
  },
  {
    id: 'text',
    label: '文本工具',
    description: '文本处理和数据工具',
    pluginIds: ['plugin-text-ops', 'plugin-color-converter'],
  },
  {
    id: 'network',
    label: '网络工具',
    description: '网络和连接测试工具',
    pluginIds: ['plugin-website-latency'],
  },
  {
    id: 'utility',
    label: '实用工具',
    description: '通用实用工具',
    pluginIds: [
      'plugin-todo-list',
      'plugin-random-picker',
      'plugin-example-hello-world',
    ],
  },
] as const
