import type { PluginManifestEntry } from '@flow-tool/sdk'

export const builtInManifests: PluginManifestEntry[] = [
  {
    id: 'plugin-example-hello-world',
    name: 'Hello World Plugin',
    version: '0.0.1',
    type: 'app',
    permissions: ['network', 'storage', 'notification'],
    loader: () => import('@plugins/plugin-example-hello-world'),
  },
  {
    id: 'plugin-todo-list',
    name: 'Todo List',
    version: '0.0.1',
    type: 'app',
    permissions: ['storage'],
    category: '实用工具',
    tags: ['todo', 'list', 'task'],
    loader: () => import('@plugins/plugin-todo-list'),
  },
  {
    id: 'plugin-website-latency',
    name: '网站延迟测试',
    version: '0.1.0',
    description: '测试常用网站的网络延迟（Ping）',
    type: 'app',
    permissions: ['network'],
    tags: ['network', 'latency', 'ping'],
    category: '网络工具',
    loader: () => import('@plugins/plugin-website-latency'),
  },
  {
    id: 'plugin-uuid-generator',
    name: 'UUID 生成器',
    version: '0.1.0',
    description: '在线生成随机 UUID v4',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['uuid', 'random', 'generator'],
    category: '开发工具',
    loader: () => import('@plugins/plugin-uuid-generator'),
  },
  {
    id: 'plugin-image-base64',
    name: '图片 Base64 互转',
    version: '0.1.0',
    description: '在线图片与 Base64 编码互相转换',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['image', 'base64', 'converter'],
    category: '编码工具',
    loader: () => import('@plugins/plugin-image-base64'),
  },
  {
    id: 'plugin-random-picker',
    name: '随机点名',
    version: '0.1.0',
    description: '在线名单随机点名工具',
    type: 'app',
    permissions: [],
    tags: ['random', 'picker', 'name'],
    category: '实用工具',
    loader: () => import('@plugins/plugin-random-picker'),
  },
  {
    id: 'plugin-text-ops',
    name: '文本集合运算',
    version: '0.1.0',
    description: '计算文本的交集、差集、并集',
    type: 'app',
    permissions: ['clipboard'],
    tags: ['text', 'set', 'intersection', 'union', 'difference'],
    category: '文本工具',
    loader: () => import('@plugins/plugin-text-ops'),
  },
  {
    id: 'plugin-example-run-hello',
    name: 'run hello',
    version: '0.0.1',
    type: 'tool',
    loader: () => import('@plugins/plugin-example-run-hello'),
  },
]

export const pluginCategories = [
  {
    id: 'text',
    label: 'Text & Data',
    description: 'Text processing and data tools',
    pluginIds: ['plugin-text-ops', 'plugin-uuid-generator'],
  },
  {
    id: 'image',
    label: 'Image',
    description: 'Image processing tools',
    pluginIds: ['plugin-image-base64'],
  },
  {
    id: 'network',
    label: 'Network',
    description: 'Network and connectivity tools',
    pluginIds: ['plugin-website-latency'],
  },
  {
    id: 'utility',
    label: 'Utility',
    description: 'General purpose tools',
    pluginIds: [
      'plugin-todo-list',
      'plugin-random-picker',
      'plugin-example-hello-world',
    ],
  },
] as const
