// Generated from Rust. Do not edit.
export const PROTOCOL_MAJOR = 1 as const
export const CLIENT_VERSION = '0.1.0' as const
// This file has been generated by Specta. Do not edit this file manually.
export type BootstrapPolicy = {
	coldStart: boolean,
};

export type Call = { method: "session.open"; payload: OpenSession } | { method: "runtime.status" } | { method: "plugins.list" } | { method: "jobs.submit"; payload: SubmitJob } | { method: "jobs.status"; payload: JobKey } | { method: "jobs.cancel"; payload: JobKey } | { method: "jobs.events"; payload: EventCursor } | { method: "data.read"; payload: DataRead } | { method: "data.write"; payload: DataWrite } | { method: "data.transaction"; payload: DataTransaction } | { method: "data.import-legacy"; payload: DataImport } | { method: "permissions.list" } | { method: "permissions.grant"; payload: PermissionGrant } | { method: "permissions.revoke"; payload: PermissionKey } | { method: "policy.set"; payload: BootstrapPolicy } | { method: "policy.import"; payload: PolicyImport } | { method: "runtime.stop" };

/**
 *  Narrow operations: no caller/plugin/namespace, raw paths, SQL, argv or env.
 *  File handles and tool locks must be issued by a future Host adapter.
 */
export type CapabilityOperation = { operation: "file-read"; parameters: {
	handle: string,
} } | { operation: "file-create"; parameters: {
	handle: string,
} } | { operation: "file-replace"; parameters: {
	handle: string,
} } | { operation: "file-delete"; parameters: {
	handle: string,
} } | { operation: "network-read"; parameters: {
	origin: string,
	method: ReadMethod,
} } | { operation: "network-send"; parameters: {
	origin: string,
	method: SendMethod,
} } | { operation: "data-read"; parameters: {
	key: string,
} } | { operation: "data-write"; parameters: {
	key: string,
} } | { operation: "clipboard-read" } | { operation: "clipboard-write" } | { operation: "tool-execute"; parameters: {
	lock: string,
	action: string,
} };

export type CommandIdentity = {
	caller: string,
	publisher: string,
	pluginId: string,
	version: string,
	packageDigest: string,
	commandId: string,
};

export type DataImport = {
	pluginId: string,
	import: LegacyImport,
};

export type DataMutation = {
	key: string,
	expectedRevision: number,
	value: unknown,
};

export type DataRead = {
	pluginId: string,
	key: string,
};

export type DataSnapshot = {
	key: string,
	revision: number,
	value: unknown,
};

export type DataTransaction = {
	pluginId: string,
	mutations: DataMutation[],
};

export type DataWrite = {
	pluginId: string,
	mutation: DataMutation,
};

export type ErrorCode = "PROTOCOL_MISMATCH" | "CLIENT_INCOMPATIBLE" | "FRAME_TOO_LARGE" | "INVALID_REQUEST" | "SESSION_INVALID" | "INSTANCE_MISMATCH" | "APPROVAL_REQUIRED" | "INTERACTION_REQUIRED" | "CAPABILITY_UNDECLARED" | "SCOPE_DENIED" | "GRANT_REVOKED" | "BUDGET_EXCEEDED" | "REVISION_CONFLICT" | "STORE_BUSY" | "STORE_CORRUPT" | "SCHEMA_UNSUPPORTED" | "STORAGE_FAILED" | "COLD_START_DENIED" | "PLUGIN_NOT_FOUND" | "INPUT_INVALID" | "JOB_NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "TIMEOUT" | "ABORTED" | "EXECUTION_FAILED" | "OUTPUT_INVALID" | "RUNTIME_BUSY" | "RUNTIME_DISCONNECTED" | "INVALID_RESPONSE";

export type EventCursor = {
	runId: string,
	afterSequence: number,
};

export type ExecutionOutcome = ({ success: boolean; data: unknown }) & { error?: never } | ({ success: boolean; error: RuntimeError }) & { data?: never };

/**  Versioned extension of PluginExecutionResult; a receipt is a different type. */
export type ExecutionResult = {
	formatVersion: number,
	runId: string,
	pluginId: string,
	pluginVersion: string,
	startedAt: number | null,
	finishedAt: number | null,
	durationMs: number | null,
	inputSummary: InputSummary,
} & ExecutionOutcome;

export type GrantTarget = "cli" | "desktop";

export type InputSummary = {
	kind: string,
	size: number,
};

export type JobEvent = {
	runId: string,
	sequence: number,
	state: JobState,
};

export type JobKey = {
	runId: string,
};

export type JobReceipt = {
	formatVersion: number,
	receiptType: string,
	runId: string,
	instanceId: string,
	acceptedAt: number | null,
};

export type JobSnapshot = {
	formatVersion: number,
	runId: string,
	parentRunId: string | null,
	rootCaller: string,
	pluginId: string,
	commandId: string,
	packageVersion: string,
	packageDigest: string,
	dependencyLock: string,
	deadline: number | null,
	grantEpoch: number,
	resources: unknown,
	state: JobState,
	sequence: number,
	result: ExecutionResult | null,
};

export type JobState = "accepted" | "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled" | "interrupted";

export type LegacyImport = {
	source: LegacySource,
	sourceDigest: string,
	value: unknown,
};

export type LegacySource = "cli-v0" | "desktop-localstorage-v1" | "web-localstorage-v1";

export type OpenSession = {
	token: string,
	clientVersion: string,
	expectedInstanceId: string | null,
};

export type Outcome = { type: "session"; data: SessionProof } | { type: "status"; data: RuntimeStatus } | { type: "plugins"; data: PluginStatus[] } | { type: "receipt"; data: JobReceipt } | { type: "job"; data: JobSnapshot } | { type: "events"; data: JobEvent[] } | { type: "data"; data: DataSnapshot } | { type: "data-batch"; data: DataSnapshot[] } | { type: "permissions"; data: PermissionRecord[] } | { type: "policy"; data: BootstrapPolicy } | { type: "stopping" } | { type: "error"; data: RuntimeError };

export type PermissionGrant = {
	pluginId: string,
	commandId: string,
	target: GrantTarget,
	packageDigest: string,
	effects: string[],
	scopes: Scope[],
	expiresAt: number | null,
	maxCalls: number,
	coldStart: boolean,
	background: boolean,
};

export type PermissionKey = {
	pluginId: string,
	commandId: string,
	target: GrantTarget,
};

export type PermissionRecord = {
	identity: CommandIdentity,
	epoch: number,
	grant: PermissionGrant | null,
};

export type PluginStatus = {
	pluginId: string,
	version: string,
	installed: boolean,
	enabled: boolean,
	running: boolean,
};

export type PolicyImport = {
	formatVersion: number,
	coldStart: boolean,
	grants: PermissionGrant[],
};

export type ReadMethod = "GET" | "HEAD";

export type Request = {
	version: number,
	requestId: string,
	session: SessionProof | null,
	call: Call,
};

export type Response = {
	version: number,
	requestId: string,
	outcome: Outcome,
};

export type RuntimeError = {
	code: ErrorCode,
};

export type RuntimeStatus = {
	instanceId: string,
	mode: string,
	jobs: number,
};

/**  Exact, Host-approved scopes; there are no wildcard grants. */
export type Scope = { kind: "file-handle"; scope: string } | { kind: "network-read"; scope: {
	origin: string,
	method: ReadMethod,
} } | { kind: "network-send"; scope: {
	origin: string,
	method: SendMethod,
} } | { kind: "plugin-data"; scope: {
	key_prefix: string,
} } | { kind: "clipboard" } | { kind: "tool-lock"; scope: {
	lock: string,
	action: string,
} };

export type SendMethod = "POST" | "PUT" | "PATCH" | "DELETE";

export type SessionProof = {
	sessionId: string,
	instanceId: string,
};

export type SubmitJob = {
	pluginId: string,
	commandId: string,
	input: unknown,
	idempotencyKey: string,
	background: boolean,
	deadline: number | null,
};
