// Generated from Rust. Do not edit.
export const PROTOCOL_MAJOR = 1 as const
export const CLIENT_VERSION = '0.1.0' as const
// This file has been generated by Specta. Do not edit this file manually.
export type Call = { method: "session.open"; payload: OpenSession } | { method: "runtime.status" } | { method: "plugins.list" } | { method: "jobs.submit"; payload: SubmitJob } | { method: "jobs.status"; payload: JobKey } | { method: "jobs.cancel"; payload: JobKey } | { method: "jobs.events"; payload: EventCursor };

export type ErrorCode = "PROTOCOL_MISMATCH" | "CLIENT_INCOMPATIBLE" | "FRAME_TOO_LARGE" | "INVALID_REQUEST" | "SESSION_INVALID" | "INSTANCE_MISMATCH" | "APPROVAL_REQUIRED" | "PLUGIN_NOT_FOUND" | "INPUT_INVALID" | "JOB_NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "TIMEOUT" | "ABORTED" | "EXECUTION_FAILED" | "OUTPUT_INVALID" | "RUNTIME_BUSY" | "RUNTIME_DISCONNECTED" | "INVALID_RESPONSE";

export type EventCursor = {
	runId: string,
	afterSequence: number,
};

export type ExecutionOutcome = ({ success: boolean; data: unknown }) & { error?: never } | ({ success: boolean; error: RuntimeError }) & { data?: never };

/**  Versioned extension of PluginExecutionResult; a receipt is a different type. */
export type ExecutionResult = {
	formatVersion: number,
	runId: string,
	pluginId: string,
	pluginVersion: string,
	startedAt: number | null,
	finishedAt: number | null,
	durationMs: number | null,
	inputSummary: InputSummary,
} & ExecutionOutcome;

export type InputSummary = {
	kind: string,
	size: number,
};

export type JobEvent = {
	runId: string,
	sequence: number,
	state: JobState,
};

export type JobKey = {
	runId: string,
};

export type JobReceipt = {
	formatVersion: number,
	receiptType: string,
	runId: string,
	instanceId: string,
	acceptedAt: number | null,
};

export type JobSnapshot = {
	formatVersion: number,
	runId: string,
	parentRunId: string | null,
	rootCaller: string,
	pluginId: string,
	commandId: string,
	packageVersion: string,
	packageDigest: string,
	dependencyLock: string,
	deadline: number | null,
	grantEpoch: number,
	resources: unknown,
	state: JobState,
	sequence: number,
	result: ExecutionResult | null,
};

export type JobState = "accepted" | "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled" | "interrupted";

export type OpenSession = {
	token: string,
	clientVersion: string,
	expectedInstanceId: string | null,
};

export type Outcome = { type: "session"; data: SessionProof } | { type: "status"; data: RuntimeStatus } | { type: "plugins"; data: PluginStatus[] } | { type: "receipt"; data: JobReceipt } | { type: "job"; data: JobSnapshot } | { type: "events"; data: JobEvent[] } | { type: "error"; data: RuntimeError };

export type PluginStatus = {
	pluginId: string,
	version: string,
	installed: boolean,
	enabled: boolean,
	running: boolean,
};

export type Request = {
	version: number,
	requestId: string,
	session: SessionProof | null,
	call: Call,
};

export type Response = {
	version: number,
	requestId: string,
	outcome: Outcome,
};

export type RuntimeError = {
	code: ErrorCode,
};

export type RuntimeStatus = {
	instanceId: string,
	mode: string,
	jobs: number,
};

export type SessionProof = {
	sessionId: string,
	instanceId: string,
};

export type SubmitJob = {
	pluginId: string,
	commandId: string,
	input: unknown,
	idempotencyKey: string,
	background: boolean,
	deadline: number | null,
};
