// Generated from Rust. Do not edit.
export const PROTOCOL_MAJOR = 1 as const
export const CLIENT_VERSION = '0.3.0' as const
// This file has been generated by Specta. Do not edit this file manually.
export type BackupInfo = {
	id: string,
	bytes: number | null,
	schemaVersion: number | null,
	usable: boolean,
	errorCode: ErrorCode | null,
};

export type BootstrapPolicy = {
	coldStart: boolean,
};

export type Call = { method: "session.open"; payload: OpenSession } | { method: "runtime.status" } | { method: "plugins.list" } | { method: "dependencies.plan"; payload: DependencyPlanRequest } | { method: "dependencies.unload-plan"; payload: ProviderKey } | { method: "services.calls"; payload: JobKey } | { method: "jobs.submit"; payload: SubmitJob } | { method: "jobs.lookup"; payload: IdempotencyKey } | { method: "jobs.status"; payload: JobKey } | { method: "jobs.diagnose"; payload: JobKey } | { method: "jobs.list" } | { method: "jobs.cancel"; payload: JobKey } | { method: "jobs.events"; payload: EventCursor } | { method: "data.read"; payload: DataRead } | { method: "data.write"; payload: DataWrite } | { method: "data.transaction"; payload: DataTransaction } | { method: "data.import-legacy"; payload: DataImport } | { method: "permissions.list" } | { method: "permissions.grant"; payload: PermissionGrant } | { method: "permissions.revoke"; payload: PermissionKey } | { method: "policy.set"; payload: BootstrapPolicy } | { method: "policy.import"; payload: PolicyImport } | { method: "runtime.stop" };

/**
 *  Narrow operations: no caller/plugin/namespace, raw paths, SQL, argv or env.
 *  File handles and tool locks must be issued by a future Host adapter.
 */
export type CapabilityOperation = { operation: "file-read"; parameters: {
	handle: string,
} } | { operation: "file-create"; parameters: {
	handle: string,
} } | { operation: "file-replace"; parameters: {
	handle: string,
} } | { operation: "file-delete"; parameters: {
	handle: string,
} } | { operation: "network-read"; parameters: {
	origin: string,
	method: ReadMethod,
} } | { operation: "network-send"; parameters: {
	origin: string,
	method: SendMethod,
} } | { operation: "data-read"; parameters: {
	key: string,
} } | { operation: "data-write"; parameters: {
	key: string,
} } | { operation: "clipboard-read" } | { operation: "clipboard-write" } | { operation: "tool-execute"; parameters: {
	lock: string,
	action: string,
} };

export type CommandIdentity = {
	caller: string,
	publisher: string,
	pluginId: string,
	version: string,
	packageDigest: string,
	commandId: string,
};

export type DataImport = {
	pluginId: string,
	import: LegacyImport,
};

export type DataMutation = {
	key: string,
	expectedRevision: number,
	value: unknown,
};

export type DataRead = {
	pluginId: string,
	key: string,
};

export type DataSnapshot = {
	key: string,
	revision: number,
	value: unknown,
};

export type DataTransaction = {
	pluginId: string,
	mutations: DataMutation[],
};

export type DataWrite = {
	pluginId: string,
	mutation: DataMutation,
};

/**
 *  Service edges form the provider DAG. Tool pins are leaves, retaining the exact
 *  consumer and artifact separately without activating any plugin provider.
 */
export type DependencyEdge = {
	consumer: DependencyIdentity,
	provider: DependencyIdentity,
	service: string,
};

export type DependencyIdentity = {
	publisher: string,
	id: string,
};

/**
 *  Value pins, never grants, executable paths, installation or activation receipts.
 *  The digest binds every other field and excludes the digest field itself.
 */
export type DependencyLock = {
	formatVersion: number,
	digest: string,
	target: DependencyTarget,
	roots: DependencyIdentity[],
	packages: PackagePin[],
	services: ServicePin[],
	tools: ToolPin[],
	edges: DependencyEdge[],
	/**  Providers before consumers; deterministic identity order breaks ties. */
	topology: DependencyIdentity[],
	/**  Direct service consumers, including providers without consumers. */
	reverseDependencies: ReverseDependency[],
};

export type DependencyPlan = {
	formatVersion: number,
	mode: string,
	lock: DependencyLock,
};

/**  Roots only: package inventory, identities and target are Host-owned. */
export type DependencyPlanRequest = {
	pluginIds: string[],
};

export type DependencyTarget = {
	platform: string,
	arch: string,
};

export type ErrorCode = "PROTOCOL_MISMATCH" | "CLIENT_INCOMPATIBLE" | "FRAME_TOO_LARGE" | "INVALID_REQUEST" | "SESSION_INVALID" | "INSTANCE_MISMATCH" | "APPROVAL_REQUIRED" | "INTERACTION_REQUIRED" | "CAPABILITY_UNDECLARED" | "SCOPE_DENIED" | "GRANT_REVOKED" | "BUDGET_EXCEEDED" | "REVISION_CONFLICT" | "STORE_BUSY" | "STORE_CORRUPT" | "RECOVERY_PENDING" | "SCHEMA_UNSUPPORTED" | "STORAGE_FAILED" | "ACCEPTANCE_UNKNOWN" | "EXECUTION_INTERRUPTED" | "RESULT_EXPIRED" | "COLD_START_DENIED" | "PLUGIN_NOT_FOUND" | "INPUT_INVALID" | "JOB_NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "TIMEOUT" | "ABORTED" | "EXECUTION_FAILED" | "OUTPUT_INVALID" | "RUNTIME_BUSY" | "RUNTIME_DISCONNECTED" | "INVALID_RESPONSE" | "DEPENDENCY_INVALID" | "DEPENDENCY_MISSING" | "DEPENDENCY_CONFLICT" | "DEPENDENCY_DUPLICATE_PROVIDER" | "DEPENDENCY_CYCLE" | "DEPENDENCY_PLATFORM_MISMATCH" | "DEPENDENCY_ARTIFACT_MISMATCH" | "DEPENDENCY_BUDGET_EXCEEDED";

export type EventCursor = {
	runId: string,
	afterSequence: number,
};

export type ExecutionOutcome = ({ success: boolean; data: unknown }) & { error?: never } | ({ success: boolean; error: RuntimeError }) & { data?: never };

/**  Versioned extension of PluginExecutionResult; a receipt is a different type. */
export type ExecutionResult = {
	formatVersion: number,
	runId: string,
	pluginId: string,
	pluginVersion: string,
	startedAt: number | null,
	finishedAt: number | null,
	durationMs: number | null,
	inputSummary: InputSummary,
} & ExecutionOutcome;

export type GrantTarget = "cli" | "desktop";

export type IdempotencyKey = {
	idempotencyKey: string,
};

export type InputSummary = {
	kind: string,
	size: number,
};

export type JobEvent = {
	runId: string,
	sequence: number,
	state: JobState,
};

export type JobKey = {
	runId: string,
};

export type JobReceipt = {
	formatVersion: number,
	receiptType: string,
	runId: string,
	instanceId: string,
	acceptedAt: number | null,
};

export type JobSnapshot = {
	formatVersion: number,
	runId: string,
	parentRunId: string | null,
	rootCaller: string,
	pluginId: string,
	commandId: string,
	packageVersion: string,
	packageDigest: string,
	dependencyLock: string,
	deadline: number | null,
	grantEpoch: number,
	resources: unknown,
	state: JobState,
	sequence: number,
	result: ExecutionResult | null,
};

export type JobState = "accepted" | "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled" | "interrupted";

export type LegacyImport = {
	source: LegacySource,
	sourceDigest: string,
	value: unknown,
};

export type LegacySource = "cli-v0" | "desktop-localstorage-v1" | "web-localstorage-v1";

export type OpenSession = {
	token: string,
	clientVersion: string,
	expectedInstanceId: string | null,
};

export type Outcome = { type: "session"; data: SessionProof } | { type: "status"; data: RuntimeStatus } | { type: "plugins"; data: PluginStatus[] } | { type: "dependency-plan"; data: DependencyPlan } | { type: "provider-change-plan"; data: ProviderChangePlan } | { type: "service-calls"; data: ServiceCallDiagnostic[] } | { type: "receipt"; data: JobReceipt } | { type: "job"; data: JobSnapshot } | { type: "jobs"; data: JobSnapshot[] } | { type: "diagnostic"; data: RunDiagnostic } | { type: "events"; data: JobEvent[] } | { type: "data"; data: DataSnapshot } | { type: "data-batch"; data: DataSnapshot[] } | { type: "permissions"; data: PermissionRecord[] } | { type: "policy"; data: BootstrapPolicy } | { type: "stopping" } | { type: "error"; data: RuntimeError };

export type PackagePin = {
	publisher: string,
	id: string,
	version: string,
	digest: string,
};

export type PermissionGrant = {
	pluginId: string,
	commandId: string,
	target: GrantTarget,
	packageDigest: string,
	effects: string[],
	scopes: Scope[],
	expiresAt: number | null,
	maxCalls: number,
	coldStart: boolean,
	background: boolean,
};

export type PermissionKey = {
	pluginId: string,
	commandId: string,
	target: GrantTarget,
};

export type PermissionRecord = {
	identity: CommandIdentity,
	epoch: number,
	grant: PermissionGrant | null,
};

export type PluginStatus = {
	pluginId: string,
	version: string,
	packageDigest: string,
	installed: boolean,
	enabled: boolean,
	running: boolean,
};

export type PolicyImport = {
	formatVersion: number,
	coldStart: boolean,
	grants: PermissionGrant[],
};

export type ProviderChangePlan = {
	mode: string,
	digest: string,
	provider: PackagePin,
	replacement: PackagePin | null,
	consumers: DependencyIdentity[],
	affectedLocks: string[],
};

export type ProviderKey = {
	pluginId: string,
};

export type ReadMethod = "GET" | "HEAD";

export type RecoveryPhase = "prepared" | "replaced" | "complete";

export type RecoveryReceipt = {
	recoveryId: string,
	backupId: string,
	phase: RecoveryPhase,
	grantsRevoked: boolean,
	payloadsQuarantined: boolean,
};

export type Request = {
	version: number,
	requestId: string,
	session: SessionProof | null,
	call: Call,
};

export type Response = {
	version: number,
	requestId: string,
	outcome: Outcome,
};

export type ReverseDependency = {
	provider: DependencyIdentity,
	consumers: DependencyIdentity[],
};

/**  Metadata allowlist only; never payloads, arbitrary messages, paths or credentials. */
export type RunDiagnostic = {
	formatVersion: number,
	runId: string,
	parentRunId: string | null,
	rootCaller: string,
	pluginId: string,
	commandId: string,
	packageVersion: string,
	packageDigest: string,
	dependencyLock: string,
	grantEpoch: number,
	state: JobState,
	sequence: number,
	acceptedAt: number | null,
	startedAt: number | null,
	finishedAt: number | null,
	durationMs: number | null,
	background: boolean,
	failureCode: ErrorCode | null,
	resultExpired: boolean,
	requiresReview: boolean,
};

export type RuntimeError = {
	code: ErrorCode,
};

export type RuntimeStatus = {
	instanceId: string,
	mode: string,
	jobs: number,
	activeJobs: number,
};

/**  Exact, Host-approved scopes; there are no wildcard grants. */
export type Scope = { kind: "file-handle"; scope: string } | { kind: "network-read"; scope: {
	origin: string,
	method: ReadMethod,
} } | { kind: "network-send"; scope: {
	origin: string,
	method: SendMethod,
} } | { kind: "plugin-data"; scope: {
	key_prefix: string,
} } | { kind: "clipboard" } | { kind: "tool-lock"; scope: {
	lock: string,
	action: string,
} };

export type SendMethod = "POST" | "PUT" | "PATCH" | "DELETE";

export type ServiceCallDiagnostic = {
	runId: string,
	parentRunId: string,
	rootRunId: string,
	rootCaller: string,
	consumer: DependencyIdentity,
	provider: PackagePin,
	service: string,
	operation: string,
	dependencyLock: string,
	deadline: number | null,
	state: string,
	failureCode: ErrorCode | null,
};

export type ServicePin = {
	consumer: DependencyIdentity,
	provider: PackagePin,
	service: string,
	version: string,
};

export type SessionProof = {
	sessionId: string,
	instanceId: string,
};

/**  Offline T0 storage actions; never part of business Call or caller-selected paths. */
export type StorageAction = { operation: "list" } | { operation: "create" } | { operation: "restore"; parameters: {
	backupId: string,
} } | { operation: "retry" };

export type StorageReport = {
	formatVersion: number,
	backups: BackupInfo[],
	recovery: RecoveryReceipt | null,
};

export type SubmitJob = {
	pluginId: string,
	commandId: string,
	input: unknown,
	idempotencyKey: string,
	background: boolean,
	deadline: number | null,
};

export type ToolPin = {
	consumer: DependencyIdentity,
	publisher: string,
	id: string,
	version: string,
	target: DependencyTarget,
	buildFlavor: string,
	digest: string,
};
