import type { PluginManifestV1 } from '../packages/sdk/src/manifest'
import type { FormatConfig } from 'oxfmt'

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { format } from 'oxfmt'

import {
  commandFlags,
  commandExample,
} from '../packages/cli/src/command-schema'
import {
  parsePluginManifest,
  commandIdentity,
} from '../packages/sdk/src/manifest'

export function renderCommandDocs(manifests: PluginManifestV1[]) {
  const lines = [
    '# Built-in command reference (Manifest v1)',
    '',
    'Generated from actual compiled T1 manifests; do not edit this file manually.',
    'Run `bun run generate:command-docs` after `build:packages`.',
    'Discovery and schemas are declarations, not signatures, grants or security approval.',
    'Examples satisfy the finite input schema; runtime validators and business semantics still apply.',
    'See [CLI contract](./cli-contract-v1.md) for JSON, flags, batch and stable errors.',
    '',
  ]
  for (const manifest of [...manifests].sort((a, b) =>
    a.id.localeCompare(b.id)
  )) {
    for (const command of manifest.commands) {
      lines.push(
        `## ${commandIdentity(manifest, command)}`,
        '',
        command.description,
        '',
        `Version: ${manifest.version}; maturity: ${manifest.maturity}.`,
        `Targets: ${manifest.targets.map(item => item.platform + '/' + item.arch).join(', ')}.`,
        `Headless: ${command.headless}; cold start: ${command.supportsColdStart}; interaction: ${command.interaction}.`,
        `Effects: ${command.effects.join(', ') || 'none'}.`,
        `Permission requests: ${JSON.stringify(command.permissions)}.`,
        `Runtime validation: ${JSON.stringify(command.runtimeValidation)}.`,
        `Budgets: ${JSON.stringify(command.resources)}.`,
        '',
        '```powershell',
        `bun run packages/cli/dist/cli.mjs describe ${manifest.id} ${command.id} --format json`,
        '```',
        '',
        '| Flag | Type | Required | Default | Description |',
        '| --- | --- | --- | --- | --- |'
      )
      for (const field of commandFlags(command)) {
        const clean = (value: string) =>
          value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ')
        lines.push(
          `| ${field.flag} | ${field.type} | ${field.required} | ${clean(JSON.stringify(field.default) ?? '')} | ${clean(field.description ?? '')} |`
        )
      }
      lines.push(
        '',
        'Schema-valid input example:',
        '',
        '```json',
        JSON.stringify(commandExample(command), null, 2),
        '```',
        '',
        'Input schema:',
        '',
        '```json',
        JSON.stringify(command.inputSchema, null, 2),
        '```',
        '',
        'Output schema:',
        '',
        '```json',
        JSON.stringify(command.outputSchema, null, 2),
        '```',
        ''
      )
    }
  }
  return lines.join('\n')
}

export async function generateCommandDocs(check = false) {
  const root = resolve(import.meta.dir, '..')
  const catalog: unknown = JSON.parse(
    readFileSync(
      resolve(root, 'plugins/.generated/builtin-manifests.json'),
      'utf8'
    )
  )
  if (
    !catalog ||
    typeof catalog !== 'object' ||
    !('formatVersion' in catalog) ||
    catalog.formatVersion !== 1 ||
    !('plugins' in catalog) ||
    !Array.isArray(catalog.plugins)
  )
    throw new Error('Invalid command catalog')
  const manifests = catalog.plugins.map(value => parsePluginManifest(value))
  const path = resolve(root, 'docs/builtin-commands.md')
  const config = JSON.parse(
    readFileSync(resolve(root, '.oxfmtrc.json'), 'utf8')
  ) as FormatConfig
  const output = await format(path, renderCommandDocs(manifests), config)
  if (output.errors.length)
    throw new Error('Cannot format command documentation')
  if (check) {
    if (
      readFileSync(path, 'utf8').replace(/\r\n/g, '\n') !==
      output.code.replace(/\r\n/g, '\n')
    )
      throw new Error('Generated command documentation is stale')
  } else writeFileSync(path, output.code)
}

if (import.meta.main)
  await generateCommandDocs(process.argv.includes('--check'))
